version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quizDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  pgdata:
